name: Daily Appointment Booking

on:
  schedule:
    - cron: '55 18 * * *'
    - cron: '55 19 * * *'
    - cron: '55 20 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run appointment booking script
        run: node index.js
